resolver: lts-7.14
compiler: ghcjs-0.2.1.9007014_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007014_ghc-8.0.1:
           url: http://ghcjs.tolysz.org/ghc-8.0-2016-12-25-lts-7.14-9007014.tar.gz
           sha1: 0d2ebe0931b29adca7cb9d9b9f77d60095bfb864

packages:
- .
- ../gelatin
- ../gelatin-shaders

extra-deps:
- ghcjs-dom-0.3.1.0
- ghcjs-dom-jsffi-0.3.1.0
